







	



.build/alamode/SHT1x-master/SHT1x.d : lib/SHT1x-master/SHT1x.cpp
	@mkdir -p .build/alamode/SHT1x-master
	@/usr/bin/avr-gcc -mmcu=atmega328p -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/variants/standard -I/usr/share/arduino/hardware/arduino/cores/arduino -Ilib/Sensirion -Ilib/SHT1x-master -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility -I/usr/share/arduino/libraries/SoftwareSerial  -MM $^ > $@
	
	@printf ".build/alamode/SHT1x-master/SHT1x.d .build/alamode/SHT1x-master/" | cat - $@ > $@~ && mv $@~ $@



.build/alamode/SHT1x-master/dependencies.d : .build/alamode/SHT1x-master/SHT1x.d
	@echo [96mScanning dependencies of SHT1x-master[0m
	@mkdir -p .build/alamode/SHT1x-master
	@cat $^ > $@;

all : .build/alamode/SHT1x-master/dependencies.d
	@true

